services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hades        
      MYSQL_ROOT_USER: juan            
      MYSQL_DATABASE: mydatabase       
    ports:
      - "3306:3306"                    
    volumes:
      - mysql_data:/var/lib/mysql      
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "3000:3000" 
    volumes:
      - ./backend:/app 
    depends_on:
      - mysql
    networks:
      - app_network

  ionic-ui:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: ionic-ui
    ports:
      - "8100:8100"
    volumes:
      - ./frontend:/src/frontend/dam
    depends_on:
      - backend
    networks:
      - app_network


volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
